version: "3.8"

# Services
services:
  # Server
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"

  # Client
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ./frontend/.env
    ports:
      - "80:80"
    depends_on:
      - server
