version: "3.8"

# Services
services:
  # Server
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 5000
      JWT_SECRET: jose123
      MONGO_HOST: host
      MONGO_PORT: 27017
      MONGO_DB: markerplace
      MONGO_USER: admin
      MONGO_PASSWORD: admin
      CLOUDINARY_NAME: name
      CLOUDINARY_API_KEY: api_key
      CLOUDINARY_API_SECRET: api_secret
      SUPER_SECRET_KEY: ab12cd34e5
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  # Client
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_HOST: http://localhost
      REACT_APP_API_PORT: 5000
    ports:
      - "80:80"
    depends_on:
      - server

  # Database
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

volumes:
  data:
